export const ADD_WORD = "ADD_WORD"
export const ADD_WORD_SUCCESS = "ADD_WORD_SUCCESS"
export const ADD_WORD_FAILURE = "ADD_WORD_FAILURE"

export const GET_WORDS = "GET_WORDS"
export const GET_WORDS_SUCCESS = "GET_WORDS_SUCCESS"
export const GET_WORDS_FAILURE = "GET_WORDS_FAILURE"

export const GET_DICTS = "GET_DICTS"
export const GET_DICTS_SUCCESS = "GET_DICTS_SUCCESS"
export const GET_DICTS_FAILURE = "GET_DICTS_FAILURE"

export const GET_WORDS_BY_DICT = "GET_WORDS_BY_DICT"
export const GET_WORDS_BY_DICT_SUCCESS = "GET_WORDS_BY_DICT_SUCCESS"
export const GET_WORDS_BY_DICT_FAILURE = "GET_WORDS_BY_DICT_FAILURE"

export const DELETE_WORD = "DELETE_WORD"
export const DELETE_WORD_SUCCESS = "DELETE_WORD_SUCCESS"
export const DELETE_WORD_FAILURE = "DELETE_WORD_FAILURE"
